export const OBD_CODE_DEFINITIONS: Record<string, string> = {
  'P0101': 'Mass Air Flow (MAF) Circuit Range/Performance Problem',
  'P0113': 'Intake Air Temperature (IAT) Sensor 1 Circuit High Input',
  'P0122': 'Throttle Position Sensor (TPS) Circuit Low Input',
  'P0135': 'O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 1)',
  'P0171': 'System Too Lean (Bank 1)',
  'P0174': 'System Too Lean (Bank 2)',
  'P0300': 'Random or Multiple Cylinder Misfire Detected',
  'P0301': 'Cylinder 1 Misfire Detected',
  'P0302': 'Cylinder 2 Misfire Detected',
  'P0303': 'Cylinder 3 Misfire Detected',
  'P0304': 'Cylinder 4 Misfire Detected',
  'P0420': 'Catalyst System Efficiency Below Threshold (Bank 1)',
  'P0442': 'Evaporative Emission (EVAP) System Leak Detected (Small Leak)',
  'P0500': 'Vehicle Speed Sensor (VSS) Malfunction',
  'P0505': 'Idle Control System Malfunction',
  'P0606': 'ECM/PCM Processor Fault',
  'P0700': 'Transmission Control System Malfunction',
  'C0035': 'Left Front Wheel Speed Sensor Circuit Malfunction',
  'B0001': 'Driver Airbag Deployment Control - Stage 1',
  'U0100': 'Lost Communication With ECM/PCM',
};
